import crypto from 'node:crypto';
import fs from 'node:fs';
import http from 'node:http';
import os from 'node:os';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const requireFromAgent = createRequire(path.resolve(here, '..', '..', 'agent', 'package.json'));
const WebSocket = requireFromAgent('ws');

const MAX_SIGNAL_BYTES = 256 * 1024;
const ALLOWED_TYPES = new Set([
  'remote.signal.client_ready',
  'remote.signal.offer',
  'remote.signal.answer',
  'remote.signal.ice',
  'remote.signal.peer_left',
]);

function validSignal(role, message) {
  if (!message || typeof message !== 'object' || message.v !== 1 ||
      !ALLOWED_TYPES.has(message.type)) return false;
  if (message.type === 'remote.signal.client_ready') {
    return role === 'client';
  }
  if (message.type === 'remote.signal.offer' || message.type === 'remote.signal.answer') {
    const expectedRole = message.type === 'remote.signal.offer' ? 'host' : 'client';
    const expectedDescription = expectedRole === 'host' ? 'offer' : 'answer';
    return role === expectedRole && message.description &&
      message.description.type === expectedDescription &&
      typeof message.description.sdp === 'string' &&
      message.description.sdp.length > 0 && message.description.sdp.length <= MAX_SIGNAL_BYTES;
  }
  if (message.type === 'remote.signal.ice') {
    return message.candidate && typeof message.candidate === 'object' &&
      typeof message.candidate.candidate === 'string' &&
      message.candidate.candidate.length <= 65536;
  }
  // peer.left is generated by the broker and is never accepted from a peer.
  return false;
}

function firstLanIpv4() {
  for (const entries of Object.values(os.networkInterfaces())) {
    for (const entry of entries || []) {
      if (entry.family === 'IPv4' && !entry.internal) return entry.address;
    }
  }
  return '127.0.0.1';
}

function parseArguments(argv) {
  const options = { host: '0.0.0.0', port: 8788, selfTest: false };
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === '--self-test') options.selfTest = true;
    else if (arg === '--host' && argv[index + 1]) options.host = argv[++index];
    else if (arg === '--port' && argv[index + 1]) {
      const port = Number.parseInt(argv[++index], 10);
      if (!Number.isInteger(port) || port < 0 || port > 65535) throw new Error('invalid --port');
      options.port = port;
    } else {
      throw new Error(`unknown argument: ${arg}`);
    }
  }
  return options;
}

export async function createSignalServer(options = {}) {
  const host = options.host || '0.0.0.0';
  const port = Number.isInteger(options.port) ? options.port : 8788;
  const roomToken = options.roomToken || crypto.randomBytes(18).toString('base64url');
  const hostHtml = fs.readFileSync(path.join(here, 'host.html'));
  const phoneHtml = fs.readFileSync(path.resolve(
    here,
    '..',
    '..',
    'harmony',
    'entry',
    'src',
    'main',
    'resources',
    'rawfile',
    'remote-poc',
    'index.html',
  ));
  const peers = new Map();

  const server = http.createServer((request, response) => {
    const url = new URL(request.url || '/', 'http://127.0.0.1');
    response.setHeader('Cache-Control', 'no-store');
    response.setHeader('X-Content-Type-Options', 'nosniff');
    response.setHeader('Referrer-Policy', 'no-referrer');
    if (request.method === 'GET' && url.pathname === '/healthz') {
      response.writeHead(200, { 'Content-Type': 'application/json; charset=utf-8' });
      response.end(JSON.stringify({ ok: true, protocol_version: 1, peers: peers.size }));
      return;
    }
    if (request.method === 'GET' && url.pathname === '/host' && url.searchParams.get('room') === roomToken) {
      response.writeHead(200, {
        'Content-Type': 'text/html; charset=utf-8',
        'Content-Security-Policy': "default-src 'self'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src ws: wss:; media-src blob:",
      });
      response.end(hostHtml);
      return;
    }
    if (request.method === 'GET' && url.pathname === '/phone' && url.searchParams.get('room') === roomToken) {
      response.writeHead(200, {
        'Content-Type': 'text/html; charset=utf-8',
        'Content-Security-Policy': "default-src 'self'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src ws: wss:; media-src blob:",
      });
      response.end(phoneHtml);
      return;
    }
    response.writeHead(404, { 'Content-Type': 'text/plain; charset=utf-8' });
    response.end('Not found');
  });

  const websocketServer = new WebSocket.Server({ noServer: true, maxPayload: MAX_SIGNAL_BYTES });
  server.on('upgrade', (request, socket, head) => {
    const url = new URL(request.url || '/', 'http://127.0.0.1');
    const role = url.searchParams.get('role');
    if (url.pathname !== '/signal' || url.searchParams.get('room') !== roomToken ||
        (role !== 'host' && role !== 'client')) {
      socket.write('HTTP/1.1 403 Forbidden\r\nConnection: close\r\n\r\n');
      socket.destroy();
      return;
    }
    websocketServer.handleUpgrade(request, socket, head, (websocket) => {
      websocketServer.emit('connection', websocket, role);
    });
  });

  websocketServer.on('connection', (websocket, role) => {
    const previous = peers.get(role);
    if (previous && previous.readyState === WebSocket.OPEN) previous.close(4009, 'role replaced');
    peers.set(role, websocket);

    websocket.on('message', (raw, isBinary) => {
      if (isBinary || raw.length > MAX_SIGNAL_BYTES) {
        websocket.close(4003, 'invalid signal payload');
        return;
      }
      let message;
      try {
        message = JSON.parse(raw.toString('utf8'));
      } catch {
        websocket.close(4003, 'invalid signal json');
        return;
      }
      if (!validSignal(role, message)) {
        websocket.close(4003, 'unknown signal type');
        return;
      }
      const target = peers.get(role === 'host' ? 'client' : 'host');
      if (target && target.readyState === WebSocket.OPEN) target.send(JSON.stringify(message));
    });

    websocket.on('close', () => {
      if (peers.get(role) === websocket) peers.delete(role);
      const target = peers.get(role === 'host' ? 'client' : 'host');
      if (target && target.readyState === WebSocket.OPEN) {
        target.send(JSON.stringify({ v: 1, type: 'remote.signal.peer_left' }));
      }
    });
  });

  await new Promise((resolve, reject) => {
    server.once('error', reject);
    server.listen(port, host, resolve);
  });
  const address = server.address();
  const actualPort = typeof address === 'object' && address ? address.port : port;
  const lanIp = options.lanIp || firstLanIpv4();
  return {
    host,
    port: actualPort,
    roomToken,
    hostUrl: `http://127.0.0.1:${actualPort}/host?room=${encodeURIComponent(roomToken)}`,
    phoneBrowserUrl: `http://127.0.0.1:${actualPort}/phone?room=${encodeURIComponent(roomToken)}`,
    clientSignalUrl: `ws://${lanIp}:${actualPort}/signal?room=${encodeURIComponent(roomToken)}&role=client`,
    close: async () => {
      for (const peer of peers.values()) peer.close(1001, 'server closing');
      websocketServer.close();
      await new Promise((resolve) => server.close(resolve));
    },
  };
}

function waitForMessage(websocket) {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error('signal self-test timeout')), 3000);
    websocket.once('message', (raw) => {
      clearTimeout(timer);
      resolve(JSON.parse(raw.toString('utf8')));
    });
    websocket.once('error', (error) => {
      clearTimeout(timer);
      reject(error);
    });
  });
}

async function runSelfTest() {
  const roomToken = crypto.randomBytes(18).toString('base64url');
  const instance = await createSignalServer({ host: '127.0.0.1', port: 0, roomToken });
  const base = `ws://127.0.0.1:${instance.port}/signal?room=${roomToken}`;
  const host = new WebSocket(`${base}&role=host`);
  const client = new WebSocket(`${base}&role=client`);
  await Promise.all([
    new Promise((resolve, reject) => { host.once('open', resolve); host.once('error', reject); }),
    new Promise((resolve, reject) => { client.once('open', resolve); client.once('error', reject); }),
  ]);
  const received = waitForMessage(client);
  host.send(JSON.stringify({
    v: 1,
    type: 'remote.signal.offer',
    description: { type: 'offer', sdp: 'synthetic-self-test' },
  }));
  const message = await received;
  const passed = message.v === 1 && message.type === 'remote.signal.offer' &&
    message.description?.sdp === 'synthetic-self-test';
  host.close();
  client.close();
  await instance.close();
  process.stdout.write(JSON.stringify({
    protocol_version: 1,
    self_test: 'webrtc_signal_broker',
    passed,
    sdp_logged: false,
    persistent_state: false,
  }) + '\n');
  if (!passed) process.exitCode = 3;
}

const invokedDirectly = process.argv[1] &&
  path.resolve(process.argv[1]).toLowerCase() === fileURLToPath(import.meta.url).toLowerCase();
if (invokedDirectly) {
  const options = parseArguments(process.argv.slice(2));
  if (options.selfTest) {
    await runSelfTest();
  } else {
    const instance = await createSignalServer(options);
    process.stdout.write(JSON.stringify({
      protocol_version: 1,
      mode: 'local_webrtc_signal_lab',
      host_url: instance.hostUrl,
      phone_browser_test_url: instance.phoneBrowserUrl,
      phone_signal_url: instance.clientSignalUrl,
      media_via_server: false,
      expires_when_process_stops: true,
    }) + '\n');
  }
}
